### ISSUE TITLE
SubscriptionPrice is missing fields

### ISSUE THREAD

**Issue by marinaglancy** [PaddleHQ/paddle-python-sdk#15]
### Describe the bug

Fields in the API: https://developer.paddle.com/api-reference/subscriptions/list-subscriptions (see in the example under the items[0].price)
Fields in the SDK: https://github.com/PaddleHQ/paddle-python-sdk/blob/v0.1.3/paddle_billing/Entities/Subscriptions/SubscriptionPrice.py

Missing fields:
- type
- name
- unit_price_overrides
- custom_data
- status
- quantity {minimum, maximum}

In my case I need minimum and maximum quantity that are returned by the API but not by the SDK

### Steps to reproduce

If you call `paddle.subscriptions.list()` using the paddle-python-sdk it returns half of the price fields comparing to performing the API request directly

### Expected behavior

I expect minimum and maximum quantity for the price to be returned

### Python version

3.11

### SDK version

1.0.3

### API version

1

**Comment by marinaglancy** [comment]
Also, there are two classes: `paddle_billing.Entities.Price` and `paddle_billing.Entities.Subscriptions.SubscriptionPrice` and the first one has all the fields but the second one is truncated, I do not understand why, the API returns all price fields for the items when you get or list subscriptions

**Comment by mikeymike** [comment]
Hi @marinaglancy ... this issue was closed slightly prematurely as the fix was merged into main. We've now released this in [v0.2.0](https://github.com/PaddleHQ/paddle-python-sdk/releases/tag/v0.2.0) 👍
