### ISSUE TITLE
Customer portal sessions

### ISSUE THREAD

**Issue by Mike97M** [PaddleHQ/paddle-python-sdk#78]
### Please describe your feature request.

According to the api documentation: https://developer.paddle.com/api-reference/customer-portals/create-customer-portal-session it's possible to create customer portal session directly from the api, by providing the subscription ID, but I couldn't find this functionality in the sdk, so it would be great if it was implemented.

### Describe your solution.

Add a new function under the subscription sub-module to handle the creation of temp links to the portal.

**Comment by davidgrayston-paddle** [comment]
Hi @Mike97M :wave:

Thank you for opening this issue, we plan to add support for customer portal sessions in the next few weeks.

**Comment by davidgrayston-paddle** [comment]
Hello @Mike97M 👋 

Support for creating customer portal sessions has been included in release [`v1.2.0`](https://github.com/PaddleHQ/paddle-python-sdk/releases/tag/v1.2.0)
